### PR TITLE
checkstyle

### PR DESCRIPTION
**Pull request by Andrii-Kniaziev**
net.broscorp.checkstyle

### CODE REVIEW

**Comment by Andrii-Kniaziev** [comment]
Reopen pull request because of new bot

**Comment by Provsky** [comment]
Good)

**Comment by Andrii-Kniaziev** [comment]
The bot haven`t given me a new task)
Or should I just choose one of them from downloaded project?

**Comment by Andrii-Kniaziev** [comment]
> Good)

The bot haven`t given me a new task)
Or should I just choose one of them from downloaded project?

**Pull request closed without merging**
